create user sysadmin_test_user with sysadmin password 'Test@123';
alter session set session authorization sysadmin_test_user password 'Test@123';
select count(*) from all_columns;     
select count(*) from all_objects;       
select count(*) from all_views;          
select count(*) from check_constraints;  
select count(*) from columns;           
select count(*) from configurations;     
select count(*) from database_principals;
select count(*) from databases;          
select count(*) from foreign_key_columns;
select count(*) from foreign_keys;       
select count(*) from identity_columns; 
select count(*) from index_columns;      
select count(*) from indexes;            
select count(*) from key_constraints;    
select count(*) from objects;            
select count(*) from procedures;         
select count(*) from schemas;            
select count(*) from sequences;          
select count(*) from server_principals;  
select count(*) from synonyms;           
set d_format_behavior_compat_options = '';
select count(*) from syscolumns;
reset d_format_behavior_compat_options;
select count(*) from sysdatabases;       
select count(*) from sysforeignkeys;     
select count(*) from sysindexes;         
select count(*) from sysindexkeys;       
select count(*) from sysobjects;         
select count(*) from sysprocesses;       
select count(*) from system_objects;     
select count(*) from sysusers;           
select count(*) from tables;             
select count(*) from trigger_events;     
select count(*) from triggers;           
select count(*) from views;              

RESET SESSION AUTHORIZATION;
drop user sysadmin_test_user cascade;
